version: "3"
services:
  mysql_d:
    image: mysql:5.6
    container_name: dev_mysql_d
    ports:
      - 3302:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dcms
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data5.6:/var/lib/mysql
    networks:
      - default

  www:
    build: .
    container_name: dcms
#    command: bash -c "cd /app && php -S 0.0.0.0:8005"
    links:
      - mysql_d
    ports:
      - "8005:80"
    volumes:
      - ./www:/var/www/html/public
    networks:
      - default

  phpmyadmindcms:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_d
    ports:
      - 8004:80
    environment:
      PMA_HOST: mysql_d
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_PORT: 3302
